os: linux
dist: bionic

services:
  - docker

language: python
python:
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - docker build -t meyer1994/gitserver .
  - docker run --rm -itd -p 8000:8000 meyer1994/gitserver

script:
  - git remote add local http://localhost:8000/test
  - git push local master
  - git clone http://localhost:8000/test test

deploy:
  provider: script
  script: >
    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker push
