os: linux
dist: bionic

services:
  - docker

language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install flake8
  - docker build . -t gitserver

before_script:
  - docker run --rm --itd -p 8000:8000 gitserver
  - sleep 5
  - docker ps -a

script:
  - git clone https://github.com/git/git.git
  - cd git
  - git remote add local http://admin:admin@localhost:8000/git
  - git push local master
